// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/open-api/v2/go/models"
)

// RenewSiteTLSCertificateReader is a Reader for the RenewSiteTLSCertificate structure.
type RenewSiteTLSCertificateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RenewSiteTLSCertificateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRenewSiteTLSCertificateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRenewSiteTLSCertificateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRenewSiteTLSCertificateOK creates a RenewSiteTLSCertificateOK with default headers values
func NewRenewSiteTLSCertificateOK() *RenewSiteTLSCertificateOK {
	return &RenewSiteTLSCertificateOK{}
}

/*RenewSiteTLSCertificateOK handles this case with default header values.

OK
*/
type RenewSiteTLSCertificateOK struct {
	Payload *models.SniCertificate
}

func (o *RenewSiteTLSCertificateOK) Error() string {
	return fmt.Sprintf("[POST /sites/{site_id}/ssl/renew][%d] renewSiteTlsCertificateOK  %+v", 200, o.Payload)
}

func (o *RenewSiteTLSCertificateOK) GetPayload() *models.SniCertificate {
	return o.Payload
}

func (o *RenewSiteTLSCertificateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SniCertificate)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRenewSiteTLSCertificateDefault creates a RenewSiteTLSCertificateDefault with default headers values
func NewRenewSiteTLSCertificateDefault(code int) *RenewSiteTLSCertificateDefault {
	return &RenewSiteTLSCertificateDefault{
		_statusCode: code,
	}
}

/*RenewSiteTLSCertificateDefault handles this case with default header values.

error
*/
type RenewSiteTLSCertificateDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the renew site TLS certificate default response
func (o *RenewSiteTLSCertificateDefault) Code() int {
	return o._statusCode
}

func (o *RenewSiteTLSCertificateDefault) Error() string {
	return fmt.Sprintf("[POST /sites/{site_id}/ssl/renew][%d] renewSiteTLSCertificate default  %+v", o._statusCode, o.Payload)
}

func (o *RenewSiteTLSCertificateDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *RenewSiteTLSCertificateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
